
  version: '3.8'
  services:
    db:
      image: stock_db:latest
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=success
        - POSTGRES_PASSWORD=root
      volumes:
        - db:/var/lib/postgresql/data
  volumes:
    db:
      driver: local